name: CI

on:
  pull_request:
  push:
    branches:
      - main
      - devel
      - bepolia

jobs:
  ci:
    runs-on:
      labels: ubuntu-latest
    strategy:
      matrix:
        include:
          - job_name: lint
            command: bun run lint
            summary: "## Lint result"
          - job_name: build
            command: forge build
            summary: "## Build result"
          - job_name: coverage
            command: forge coverage --fuzz-runs 256 --report lcov --report-file ./test-forge-cover.txt
            summary: "## Coverage result"
    name: ${{ matrix.job_name }}
    steps:
      - name: Check out the repo
        uses: actions/checkout@34e114876b0b11c390a56381ad16ebd13914f8d5 # v4.3.1
        with:
          submodules: recursive

      - name: Install Foundry
        uses: foundry-rs/foundry-toolchain@c7450ba673e133f5ee30098b3b54f444d3a2ca2d # v1.8.0

      - name: Install Bun
        uses: oven-sh/setup-bun@f4d14e03ff726c06358e5557344e1da148b56cf7 # v1.2.2

      - name: Install the Node.js dependencies
        run: bun install

      - name: Execute Job Command
        run: ${{ matrix.command }}

      - name: Add Job Summary
        run: |
          echo ${{ matrix.summary }} >> $GITHUB_STEP_SUMMARY
          echo "✅ Passed" >> $GITHUB_STEP_SUMMARY

      - if: ${{ matrix.job_name == 'coverage' }}
        name: Upload coverage reports to Codecov
        uses: codecov/codecov-action@f32b3a3741e1053eb607407145bc9619351dc93b # v2.1.0
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
          files: ./test-forge-cover.txt
