name: Slither Analysis

on:
  pull_request:

jobs:
  analyze:
    runs-on: ubuntu-latest
    steps:
      # Add Docker Hub authentication with rate limiting configuration
      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USER }}
          password: ${{ secrets.DOCKERHUB_PASSWORD }}
          registry: docker.io

      - uses: actions/checkout@v4

      - uses: crytic/slither-action@v0.4.1
        with:
          fail-on: none

      - name: Slither Summary
        run: |
          echo "## Slither result" >> $GITHUB_STEP_SUMMARY
          echo "✅ Passed" >> $GITHUB_STEP_SUMMARY
