name: Tests-Merge

on:
  push:
    branches:
      - main
      - bepolia
      - devel

jobs:
  test:
    runs-on:
      labels: ubuntu-latest
    timeout-minutes: 30
    steps:
      - name: Check out the repo
        uses: actions/checkout@34e114876b0b11c390a56381ad16ebd13914f8d5 # v4.3.1
        with:
          submodules: recursive

      - name: Install Foundry
        uses: foundry-rs/foundry-toolchain@c7450ba673e133f5ee30098b3b54f444d3a2ca2d # v1.8.0

      - name: Install Bun
        uses: oven-sh/setup-bun@f4d14e03ff726c06358e5557344e1da148b56cf7 # v1.2.2

      - name: Install the Node.js dependencies
        run: bun install

      - name: Generate a fuzz seed that changes weekly to avoid burning through RPC allowance
        run: echo "FOUNDRY_FUZZ_SEED=$(echo $(($EPOCHSECONDS - $EPOCHSECONDS % 604800)))" >> $GITHUB_ENV

      - name: Run tests
        run: forge test
